---
- become: true
  hosts: web_servers
  name: Openssh_server
  tasks:
    - name: Install OpenSSH server
      apt:
        name: openssh-server
        state: present
        install_recommends: false
      notify:
        - Test and restart SSHD
    - name: Ensure Ed25519 host key is present
      command: ssh-keygen -q -t ed25519 -N "" -f ssh_host_ed25519_key
      args:
        chdir: /etc/ssh
        creates: /etc/ssh/ssh_host_ed25519_key
    - name: Generate SSHD config
      template:
        src: etc/ssh/sshd_config.j2
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: "0644"
      notify:
        - Test and restart SSHD
